In [29]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [30]:
"""
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Ans : Yes, there is a difference in the data type of the variables list_ and array_list.
      list_ is a Python list, which can contain elements of any data type.
      array_list is a NumPy array, which can only contain elements of the same data type.
      In this case all elements of list_ are of string and data type of array_list is '<U1' - Unicode string
"""
print(type(list_))
print(type(array_list))
array_list

<class 'list'>
<class 'numpy.ndarray'>


array(['1', '2', '3', '4', '5'], dtype='<U1')

In [20]:
"""
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
"""
print("Data type of each and every element of list_")
for var in list_:
  print(var , type (var))

print("Data type of each and every element of array_list")
for var in array_list:
  print(var , type (var))


Data type of each and every element of list_
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
Data type of each and every element of array_list
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


In [32]:
"""
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans : Yes there will be the difference in the data type of the elements present in both variables, list_ and array list:
      The elements in the variable list_ will have data type as "string" and
      The elements in the variable array_list will have data type as "int" and
"""
array_list = np.array(object = list_, dtype = int)

print("Data type of each and every element of list_")
for var in list_:
  print(var , type (var))

print("Data type of each and every element of array_list")
for var in array_list:
  print(var , type (var))

print("""
The elements in the variable list_ will have data type as "string" and
The elements in the variable array_list will have data type as "int" and
""")

Data type of each and every element of list_
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
Data type of each and every element of array_list
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>

The elements in the variable list_ will have data type as "string" and
The elements in the variable array_list will have data type as "int" and



In [33]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [36]:
"""
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
Ans : (i) Shape function returns a tuple that contains the dimensions of the array ( number of rows , number of columns)
      (ii) Size function returns the count of elements prsent in the array
"""
print("Shape of num_array =", num_array.shape)
print("Size of num_array =", num_array.size)

Shape of num_array = (2, 3)
Size of num_array = 6


In [41]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
Ans : numpy array which contains only zeros can be created using np.zeros function but using numpy array creation function it can be created as below:
"""
#arr1 = np.zeros((3,3))
zeros = [0,0,0]
l1 = [zeros, zeros, zeros]
print(l1)
arr1 = np.array(l1)
print(arr1)
print("Shape of arr1 =", arr1.shape)
print("Size of arr1 =", arr1.size)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape of arr1 = (3, 3)
Size of arr1 = 9


In [42]:
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
"""
identity_matrix = np.eye(5,5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
